# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbd371616340c6d68e3c43ccae1e6eed02e9ee83d951a95f48761fbb00603e55c17abc76eac8a4d7ca723ade2c2e70711fd2a1b53e3973bd9892d2d4e09146ab

test:
  secret_key_base: fdf1edcff284a8aed38222a6611846d78c83e9871eb344047e478076a4e55949e99bf9798f09bbf1b9725b785097cdf7146717441c4db48aea98cabf6e319cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
